spring.application.name=EcommerSpringbootApp
server.port=8129

#The below line will log all SQL Statements to the console
spring.jpa.show-sql=true

#The below line will format the SQL Statment in readable fashion
spring.jpa.properties.hibernate.format_sql=true

#By default H2 console will be disabled and we can enable with the below property
#spring.h2.console.enabled=true

#Below Configuration for storing the data into mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce
spring.datasource.username=root
spring.datasource.password=sivasai
spring.jpa.hibernate.ddl-auto=update


